package com.churchhistorystudio.app;

import org.json.JSONArray;
import org.json.JSONObject;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;

final class MultiAiClient {
  static final class Result {
    final String content; final int inputTokens; final int outputTokens; final double costUsd; final String provider; final String model;
    Result(String c,int i,int o,double usd,String p,String m){content=c;inputTokens=i;outputTokens=o;costUsd=usd;provider=p;model=m;}
    JSONObject usageJson(){return usageJson(inputTokens,outputTokens,costUsd,false);}
    JSONObject usageJson(int in,int out,double cost,boolean retry){JSONObject o=new JSONObject();try{o.put("provider",provider);o.put("model",model);o.put("inputTokens",in);o.put("outputTokens",out);o.put("estimatedCostUsd",Math.round(cost*1000000d)/1000000d);o.put("pricingDate","2026-08-13");o.put("includesRetry",retry);o.put("note","Estimativa baseada nos tokens reportados pela API; cobrança real pode variar por cache, tier e futuras alterações de preço.");}catch(Exception ignored){}return o;}
  }
  static String safeProvider(String p){if("openai".equalsIgnoreCase(p))return"openai";if("gemini".equalsIgnoreCase(p))return"gemini";return"deepseek";}
  static String safeModel(String provider,String model){String p=safeProvider(provider);if("openai".equals(p)){if("gpt-5.6-sol".equals(model)||"gpt-5.6-terra".equals(model)||"gpt-5.6-luna".equals(model))return model;return"gpt-5.6-terra";}if("gemini".equals(p)){if("gemini-3.1-pro-preview".equals(model)||"gemini-3.5-flash-lite".equals(model)||"gemini-3.6-flash".equals(model))return model;return"gemini-3.6-flash";}return"deepseek-v4-pro".equals(model)?"deepseek-v4-pro":"deepseek-v4-flash";}
  static Result chat(String provider,String key,String model,String system,String user,int maxTokens,boolean jsonMode)throws Exception{String p=safeProvider(provider),m=safeModel(p,model);if("openai".equals(p))return openai(key,m,system,user,maxTokens,jsonMode);if("gemini".equals(p))return gemini(key,m,system,user,maxTokens,jsonMode);return deepseek(key,m,system,user,maxTokens,jsonMode);}

  private static Result deepseek(String key,String model,String system,String user,int maxTokens,boolean jsonMode)throws Exception{
    JSONObject body=new JSONObject();body.put("model",model);JSONArray msgs=new JSONArray();msgs.put(new JSONObject().put("role","system").put("content",system));msgs.put(new JSONObject().put("role","user").put("content",user));body.put("messages",msgs);body.put("max_tokens",maxTokens);body.put("temperature",jsonMode?0.25:0.0);body.put("thinking",new JSONObject().put("type","disabled"));if(jsonMode)body.put("response_format",new JSONObject().put("type","json_object"));
    JSONObject root=post("https://api.deepseek.com/chat/completions",body,"Bearer "+key,360000);JSONArray choices=root.optJSONArray("choices");if(choices==null||choices.length()==0)throw new Exception("DeepSeek não retornou choices.");JSONObject choice=choices.getJSONObject(0);if("length".equals(choice.optString("finish_reason")))throw new Exception("Resposta DeepSeek truncada pelo limite de saída.");JSONObject msg=choice.optJSONObject("message");String content=msg==null?"":msg.optString("content","");if(content.trim().isEmpty())throw new Exception("DeepSeek retornou conteúdo vazio.");JSONObject u=root.optJSONObject("usage");int in=u==null?0:u.optInt("prompt_tokens",0),out=u==null?0:u.optInt("completion_tokens",0),hit=u==null?0:u.optInt("prompt_cache_hit_tokens",0),miss=Math.max(0,in-hit);double cost="deepseek-v4-pro".equals(model)?(hit*.003625+miss*.435+out*.87)/1e6:(hit*.0028+miss*.14+out*.28)/1e6;return new Result(content,in,out,cost,"deepseek",model);
  }

  private static Result openai(String key,String model,String system,String user,int maxTokens,boolean jsonMode)throws Exception{
    JSONObject body=new JSONObject();body.put("model",model);body.put("instructions",system);body.put("input",user);body.put("max_output_tokens",maxTokens);body.put("store",false);body.put("reasoning",new JSONObject().put("effort","low"));if(jsonMode)body.put("text",new JSONObject().put("format",new JSONObject().put("type","json_object")));
    JSONObject root=post("https://api.openai.com/v1/responses",body,"Bearer "+key,360000);if("incomplete".equals(root.optString("status")))throw new Exception("Resposta OpenAI incompleta pelo limite de saída.");StringBuilder text=new StringBuilder();JSONArray output=root.optJSONArray("output");if(output!=null)for(int i=0;i<output.length();i++){JSONObject item=output.optJSONObject(i);if(item==null||!"message".equals(item.optString("type")))continue;JSONArray content=item.optJSONArray("content");if(content==null)continue;for(int j=0;j<content.length();j++){JSONObject part=content.optJSONObject(j);if(part!=null&&"output_text".equals(part.optString("type")))text.append(part.optString("text",""));}}
    String result=text.toString();if(result.trim().isEmpty())throw new Exception("OpenAI retornou conteúdo vazio.");JSONObject u=root.optJSONObject("usage");int in=u==null?0:u.optInt("input_tokens",0),out=u==null?0:u.optInt("output_tokens",0),cached=0;if(u!=null&&u.optJSONObject("input_tokens_details")!=null)cached=u.optJSONObject("input_tokens_details").optInt("cached_tokens",0);int regular=Math.max(0,in-cached);double ip,cp,op;if("gpt-5.6-sol".equals(model)){ip=5;cp=.5;op=30;}else if("gpt-5.6-luna".equals(model)){ip=1;cp=.1;op=6;}else{ip=2.5;cp=.25;op=15;}return new Result(result,in,out,(regular*ip+cached*cp+out*op)/1e6,"openai",model);
  }

  private static Result gemini(String key,String model,String system,String user,int maxTokens,boolean jsonMode)throws Exception{
    JSONObject body=new JSONObject();body.put("systemInstruction",new JSONObject().put("parts",new JSONArray().put(new JSONObject().put("text",system))));body.put("contents",new JSONArray().put(new JSONObject().put("role","user").put("parts",new JSONArray().put(new JSONObject().put("text",user)))));JSONObject gc=new JSONObject();gc.put("maxOutputTokens",maxTokens);if(jsonMode)gc.put("responseMimeType","application/json");body.put("generationConfig",gc);String endpoint="https://generativelanguage.googleapis.com/v1beta/models/"+URLEncoder.encode(model,"UTF-8")+":generateContent?key="+URLEncoder.encode(key,"UTF-8");JSONObject root=post(endpoint,body,null,360000);JSONArray candidates=root.optJSONArray("candidates");if(candidates==null||candidates.length()==0)throw new Exception("Gemini não retornou candidates.");JSONObject cand=candidates.getJSONObject(0);if("MAX_TOKENS".equals(cand.optString("finishReason")))throw new Exception("Resposta Gemini truncada pelo limite de saída.");StringBuilder text=new StringBuilder();JSONObject cc=cand.optJSONObject("content");if(cc!=null){JSONArray parts=cc.optJSONArray("parts");if(parts!=null)for(int i=0;i<parts.length();i++)text.append(parts.getJSONObject(i).optString("text",""));}if(text.toString().trim().isEmpty())throw new Exception("Gemini retornou conteúdo vazio.");JSONObject u=root.optJSONObject("usageMetadata");int in=u==null?0:u.optInt("promptTokenCount",0),total=u==null?0:u.optInt("totalTokenCount",0),out=total>in?total-in:(u==null?0:u.optInt("candidatesTokenCount",0)+u.optInt("thoughtsTokenCount",0));double ip,op;if("gemini-3.1-pro-preview".equals(model)){ip=2;op=12;}else if("gemini-3.5-flash-lite".equals(model)){ip=.30;op=2.50;}else{ip=1.50;op=7.50;}return new Result(text.toString(),in,out,(in*ip+out*op)/1e6,"gemini",model);
  }

  static String normalizeJsonObject(String content){String t=content==null?"":content.trim();if(t.startsWith("```")){int n=t.indexOf('\n'),e=t.lastIndexOf("```");if(n>=0&&e>n)t=t.substring(n+1,e).trim();}int a=t.indexOf('{'),b=t.lastIndexOf('}');return a>=0&&b>a?t.substring(a,b+1):t;}
  static double estimateUsd(String provider,String model,int inputTokens,int outputTokens){String p=safeProvider(provider),m=safeModel(p,model);double ip,op;if("openai".equals(p)){if("gpt-5.6-sol".equals(m)){ip=5;op=30;}else if("gpt-5.6-luna".equals(m)){ip=1;op=6;}else{ip=2.5;op=15;}}else if("gemini".equals(p)){if("gemini-3.1-pro-preview".equals(m)){ip=2;op=12;}else if("gemini-3.5-flash-lite".equals(m)){ip=.30;op=2.50;}else{ip=1.50;op=7.50;}}else{if("deepseek-v4-pro".equals(m)){ip=.435;op=.87;}else{ip=.14;op=.28;}}return(inputTokens*ip+outputTokens*op)/1e6;}
  private static JSONObject post(String endpoint,JSONObject body,String auth,int timeout)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(endpoint).openConnection();c.setRequestMethod("POST");c.setConnectTimeout(30000);c.setReadTimeout(timeout);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");c.setRequestProperty("Accept","application/json");c.setRequestProperty("User-Agent","ChurchHistoryStudio-Android/0.4.6");if(auth!=null)c.setRequestProperty("Authorization",auth);try(OutputStream out=c.getOutputStream()){out.write(body.toString().getBytes(StandardCharsets.UTF_8));}int status=c.getResponseCode();InputStream s=status>=200&&status<300?c.getInputStream():c.getErrorStream();String raw=read(s,16*1024*1024);if(status<200||status>=300)throw new Exception("HTTP "+status+": "+error(raw));return new JSONObject(raw);}
  private static String read(InputStream in,int max)throws Exception{if(in==null)return"";try(InputStream x=in;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n,total=0;while((n=x.read(b))!=-1){total+=n;if(total>max)throw new Exception("Resposta maior que o limite de segurança.");out.write(b,0,n);}return new String(out.toByteArray(),StandardCharsets.UTF_8);}}
  private static String error(String raw){try{JSONObject r=new JSONObject(raw);JSONObject e=r.optJSONObject("error");if(e!=null)return e.optString("message",raw);}catch(Exception ignored){}return raw==null||raw.isEmpty()?"erro sem mensagem":raw.substring(0,Math.min(raw.length(),600));}
}
